# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('base_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Base URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'menus',
                'verbose_name': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=500, verbose_name='Order')),
                ('link_url', models.CharField(help_text='URL or URI to the content, eg /about/ or http://foo.com/', max_length=100, verbose_name='Link URL')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('login_required', models.BooleanField(help_text='Should this item only be shown to authenticated users?', verbose_name='Login required')),
                ('anonymous_only', models.BooleanField(help_text='Should this item only be shown to non-logged-in users?', verbose_name='Anonymous only')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'menu items',
                'verbose_name': 'menu item',
            },
        ),
    ]
