# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_reverse_url',
            field=models.BooleanField(default=False, help_text='Should Link URL need reverse?', verbose_name='Is reverse URL'),
        ),
    ]
