# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='Should this is a dynamic URL?', verbose_name='Dynamic mode'),
        ),
    ]
