# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='anonymous_only',
            field=models.BooleanField(default=False, help_text='Should this item only be shown to non-logged-in users?', verbose_name='Anonymous only'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(default=False, help_text='Should this item only be shown to authenticated users?', verbose_name='Login required'),
        ),
    ]
